package com.imo.operator;

import android.content.Context;
import android.content.SharedPreferences;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.util.Base64;
import java.nio.ByteBuffer;
import java.security.KeyStore;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

/** Small Keystore-backed string store. GCM IV is always generated by the Cipher/Keystore. */
public final class IMOSecureStore {
    private static final String PREF="imo_secure_store";
    private static final String ALIAS="IMO_SECURE_STORE_V1";
    private final SharedPreferences prefs;
    public IMOSecureStore(Context context){prefs=context.getSharedPreferences(PREF,Context.MODE_PRIVATE);}
    public synchronized void put(String name,String value)throws Exception{if(value==null){prefs.edit().remove(name).commit();return;}SecretKey key=getKey();Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,key);byte[] iv=c.getIV();byte[] data=c.doFinal(value.getBytes("UTF-8"));ByteBuffer b=ByteBuffer.allocate(1+iv.length+data.length);b.put((byte)iv.length).put(iv).put(data);if(!prefs.edit().putString(name,Base64.encodeToString(b.array(),Base64.NO_WRAP)).commit())throw new IllegalStateException("secure storage commit gagal");}
    public synchronized String get(String name){try{String s=prefs.getString(name,"");if(s.isEmpty())return"";byte[] packed=Base64.decode(s,Base64.NO_WRAP);ByteBuffer b=ByteBuffer.wrap(packed);int ivLen=b.get()&255;if(ivLen<12||ivLen>16)return"";byte[] iv=new byte[ivLen];b.get(iv);byte[] data=new byte[b.remaining()];b.get(data);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,getKey(),new GCMParameterSpec(128,iv));return new String(c.doFinal(data),"UTF-8");}catch(Exception e){return"";}}
    public synchronized void clear(String name){prefs.edit().remove(name).commit();}
    private SecretKey getKey()throws Exception{KeyStore ks=KeyStore.getInstance("AndroidKeyStore");ks.load(null);if(ks.containsAlias(ALIAS)){java.security.Key k=ks.getKey(ALIAS,null);if(k instanceof SecretKey)return(SecretKey)k;}KeyGenerator g=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder(ALIAS,KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).setKeySize(128).build());return g.generateKey();}
}
