package com.imo.operator;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.provider.Settings;
import android.speech.*;
import android.speech.tts.TextToSpeech;
import android.speech.tts.UtteranceProgressListener;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;
import org.json.JSONObject;
import java.util.*;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class MainActivity extends Activity {
    private static final int REQ_MIC=4101;
    private static final int BG=Color.rgb(3,10,23),CARD=Color.rgb(8,24,47),CARD2=Color.rgb(12,33,61),LINE=Color.rgb(35,82,130);
    private static final int TEXT=Color.rgb(244,247,255),MUTED=Color.rgb(155,176,204),PURPLE=Color.rgb(139,92,246),GREEN=Color.rgb(54,230,126),RED=Color.rgb(235,64,105);
    private EditText command; private TextView status,state; private Button mic,send,stop,key,access;
    private TextToSpeech tts; private SpeechRecognizer recognizer; private SecureKeyStore keyStore;
    private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private volatile boolean voiceMode=false,recognitionBusy=false,speaking=false,pendingListen=false,ttsReady=false,running=false;
    private int recognitionRetries=0;

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(Color.rgb(2,7,16));keyStore=new SecureKeyStore(this);buildUi();initTts();}

    private void initTts(){tts=new TextToSpeech(this,result->{ttsReady=result==TextToSpeech.SUCCESS;if(ttsReady){int r=tts.setLanguage(new Locale("id","ID"));if(r==TextToSpeech.LANG_MISSING_DATA||r==TextToSpeech.LANG_NOT_SUPPORTED)tts.setLanguage(Locale.getDefault());tts.setSpeechRate(.96f);tts.setPitch(1f);tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String id){speaking=true;}public void onDone(String id){speaking=false;if(pendingListen&&voiceMode){pendingListen=false;postListen(600);}}public void onError(String id){speaking=false;if(pendingListen&&voiceMode){pendingListen=false;postListen(700);}}});}else setStatus("⚠ Suara LUNA gagal diinisialisasi. Coba aktifkan mesin Text-to-Speech Android.");});}

    private void buildUi(){
        ScrollView outer=new ScrollView(this);outer.setFillViewport(true);outer.setBackgroundColor(BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(16),dp(18),dp(22));outer.addView(root);
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView orb=text("L",25,Color.WHITE,true);orb.setGravity(Gravity.CENTER);orb.setBackground(round(PURPLE,100));top.addView(orb,new LinearLayout.LayoutParams(dp(62),dp(62)));LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.setPadding(dp(13),0,0,0);names.addView(text("LUNA",29,TEXT,true));TextView sub=text("AI ANDROID DEVICE OPERATOR",11,MUTED,true);sub.setLetterSpacing(.08f);names.addView(sub);top.addView(names,new LinearLayout.LayoutParams(0,-2,1));TextView online=text("● ONLINE\nOperator Aktif",11,GREEN,true);online.setGravity(Gravity.CENTER);online.setPadding(dp(10),dp(7),dp(10),dp(7));online.setBackground(round(Color.rgb(7,42,34),30));top.addView(online);root.addView(top);
        TextView tag=text("Bicara  •  Pahami  •  Amati  •  Operasikan  •  Selesaikan",10,MUTED,false);tag.setPadding(dp(4),dp(6),0,dp(10));root.addView(tag);
        LinearLayout hello=card();hello.setOrientation(LinearLayout.HORIZONTAL);TextView av=text("◉",40,Color.WHITE,true);av.setGravity(Gravity.CENTER);av.setBackground(round(Color.rgb(24,70,150),100));hello.addView(av,new LinearLayout.LayoutParams(dp(78),dp(78)));LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);ht.setPadding(dp(14),0,0,0);ht.addView(text("Halo, saya LUNA!",18,TEXT,true));ht.addView(text("Saya siap membantu Anda mengoperasikan\nAndroid dengan suara, teks, dan perintah langsung.",12,MUTED,false));hello.addView(ht,new LinearLayout.LayoutParams(0,-2,1));root.addView(hello);
        root.addView(section("STATUS LUNA"));status=text("Siap. Simpan Gemini API Key lalu coba bertanya.",12,TEXT,false);LinearLayout sc=card();sc.addView(status,new LinearLayout.LayoutParams(-1,dp(76)));root.addView(sc);
        root.addView(section("MODE OPERATOR"));LinearLayout mode=card();mode.setOrientation(LinearLayout.HORIZONTAL);TextView brain=text("◈",25,Color.WHITE,true);brain.setGravity(Gravity.CENTER);brain.setBackground(round(PURPLE,100));mode.addView(brain,new LinearLayout.LayoutParams(dp(52),dp(52)));LinearLayout mt=new LinearLayout(this);mt.setOrientation(LinearLayout.VERTICAL);mt.setPadding(dp(12),0,0,0);mt.addView(text("Model AI",11,MUTED,false));mt.addView(text("Gemini 2.5 Flash • Free Tier",14,TEXT,true));mt.addView(text("Teks • Screenshot • Operator",10,MUTED,false));mode.addView(mt,new LinearLayout.LayoutParams(0,-2,1));TextView rd=text("SIAP",11,GREEN,true);rd.setGravity(Gravity.CENTER);rd.setPadding(dp(11),dp(6),dp(11),dp(6));rd.setBackground(stroke(Color.TRANSPARENT,GREEN,20,dp(1)));mode.addView(rd);root.addView(mode);
        root.addView(section("PROSES KERJA"));LinearLayout process=card();process.setGravity(Gravity.CENTER);String[] ic={"◉","♬","◈","⚙","✓"};String[] lb={"Dengar","Pahami","Amati","Bertindak","Verifikasi"};for(int i=0;i<5;i++){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setGravity(Gravity.CENTER);TextView x=text(ic[i],20,i==4?Color.CYAN:PURPLE,true);x.setGravity(Gravity.CENTER);x.setBackground(round(Color.rgb(26,29,88),100));p.addView(x,new LinearLayout.LayoutParams(dp(42),dp(42)));TextView y=text(lb[i],9,MUTED,true);y.setGravity(Gravity.CENTER);p.addView(y,new LinearLayout.LayoutParams(dp(58),dp(28)));process.addView(p,new LinearLayout.LayoutParams(0,-2,1));if(i<4)process.addView(text("—",14,LINE,true),new LinearLayout.LayoutParams(dp(10),dp(45)));}root.addView(process);
        root.addView(section("PERINTAH CEPAT"));LinearLayout quick=card();quick.setOrientation(LinearLayout.VERTICAL);LinearLayout q1=row();q1.addView(quickButton("▦  Buka Facebook","buka Facebook"));q1.addView(quickButton("●  Buka WhatsApp","buka WhatsApp"));q1.addView(quickButton("☁  Cek cuaca","cek cuaca hari ini"));quick.addView(q1);LinearLayout q2=row();q2.addView(quickButton("▶  Buka YouTube","buka YouTube"));q2.addView(quickButton("🔊  Volume 50","volume 50"));q2.addView(quickButton("⚙  Pengaturan","buka pengaturan"));quick.addView(q2);root.addView(quick);
        LinearLayout voice=card();voice.setOrientation(LinearLayout.VERTICAL);LinearLayout vr=row();Button tb=actionButton("⌨  TEKS",Color.TRANSPARENT,TEXT);vr.addView(tb,new LinearLayout.LayoutParams(dp(90),dp(48)));TextView wave=text(")))    ◉    (((",19,PURPLE,true);wave.setGravity(Gravity.CENTER);vr.addView(wave,new LinearLayout.LayoutParams(0,dp(48),1));mic=actionButton("MIC",Color.TRANSPARENT,TEXT);vr.addView(mic,new LinearLayout.LayoutParams(dp(105),dp(48)));voice.addView(vr);TextView vt=text("Ketuk MIC → bicara → LUNA menjawab dengan suara",11,TEXT,true);vt.setGravity(Gravity.CENTER);vt.setPadding(0,dp(5),0,0);voice.addView(vt);root.addView(voice);
        LinearLayout cr=new LinearLayout(this);cr.setGravity(Gravity.CENTER_VERTICAL);command=new EditText(this);command.setHint("Ketik pertanyaan atau perintah…");command.setHintTextColor(Color.rgb(105,128,159));command.setTextColor(TEXT);command.setTextSize(14);command.setSingleLine(true);command.setPadding(dp(16),0,dp(10),0);command.setBackground(round(CARD2,28));cr.addView(command,new LinearLayout.LayoutParams(0,dp(54),1));send=actionButton("➤",PURPLE,Color.WHITE);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(58),dp(54));sp.setMargins(dp(8),0,0,0);cr.addView(send,sp);root.addView(cr);
        LinearLayout mr=new LinearLayout(this);mr.setPadding(0,dp(12),0,0);mr.setGravity(Gravity.CENTER);Button run=actionButton("▶  JALANKAN",PURPLE,Color.WHITE);mr.addView(run,new LinearLayout.LayoutParams(0,dp(54),1));stop=actionButton("■  STOP",RED,Color.WHITE);LinearLayout.LayoutParams stp=new LinearLayout.LayoutParams(0,dp(54),.45f);stp.setMargins(dp(7),0,0,0);mr.addView(stop,stp);root.addView(mr);
        LinearLayout tools=new LinearLayout(this);tools.setPadding(0,dp(10),0,0);access=outlineButton("♿  ACCESSIBILITY");key=outlineButton("⚿  GEMINI API KEY");tools.addView(access,new LinearLayout.LayoutParams(0,dp(50),1));LinearLayout kk=new LinearLayout(this);kk.setPadding(dp(8),0,0,0);kk.addView(key,new LinearLayout.LayoutParams(-1,dp(50)));tools.addView(kk,new LinearLayout.LayoutParams(0,dp(50),1));root.addView(tools);state=text("",10,MUTED,false);root.addView(state);TextView foot=text("LUNA  •  Observe → Reason → Act → Verify\nTekan STOP kapan saja untuk menghentikan operator.",10,MUTED,false);foot.setPadding(dp(4),dp(12),dp(4),0);root.addView(foot);setContentView(outer);
        send.setOnClickListener(v->runCommand(command.getText().toString()));run.setOnClickListener(v->runCommand(command.getText().toString()));stop.setOnClickListener(v->stopAll());access.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));key.setOnClickListener(v->showKeyDialog());mic.setOnClickListener(v->toggleVoice());tb.setOnClickListener(v->{command.requestFocus();command.setSelection(command.length());});refreshState();
    }

    private Button quickButton(String label,String cmd){Button b=actionButton(label,Color.rgb(9,31,57),TEXT);b.setTextSize(9);b.setOnClickListener(v->{command.setText(cmd);runCommand(cmd);});b.setLayoutParams(new LinearLayout.LayoutParams(0,dp(42),1));return b;}
    private LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setPadding(dp(13),dp(12),dp(13),dp(12));x.setBackground(stroke(CARD,LINE,18,dp(1)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));x.setLayoutParams(p);return x;}
    private TextView section(String s){TextView v=text(s,10,MUTED,true);v.setLetterSpacing(.1f);v.setPadding(dp(4),dp(13),0,dp(3));return v;}
    private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,dp(3),0,dp(3));return r;}
    private TextView text(String s,float z,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    private Button actionButton(String s,int bg,int fg){Button b=new Button(this);b.setText(s);b.setTextColor(fg);b.setTextSize(11);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setPadding(0,0,0,0);b.setBackground(round(bg,18));return b;}
    private Button outlineButton(String s){Button b=actionButton(s,Color.TRANSPARENT,TEXT);b.setBackground(stroke(Color.TRANSPARENT,Color.rgb(57,88,124),18,dp(1)));return b;}
    private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    private GradientDrawable stroke(int c,int l,int r,int w){GradientDrawable g=round(c,r);g.setStroke(w,l);return g;}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    private void refreshState(){if(state!=null)state.setText(LunaAccessibilityService.get()!=null?(voiceMode?"● Accessibility aktif • MODE SUARA":"● Accessibility aktif"):"● Accessibility belum aktif");}

    private void showKeyDialog(){EditText e=new EditText(this);e.setHint("AIza…");e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);try{String old=keyStore.load();if(old!=null&&!old.isEmpty())e.setText(old);}catch(Exception ignored){}new AlertDialog.Builder(this).setTitle("Gemini API Key").setMessage("Masukkan API key Gemini dari Google AI Studio. Key disimpan terenkripsi di perangkat.").setView(e).setPositiveButton("Simpan",(d,w)->{try{String k=e.getText().toString().trim();if(k.isEmpty()){setStatus("⚠ API key kosong.");return;}keyStore.save(k);setStatus("✓ Gemini API key tersimpan. Sekarang coba: Halo LUNA.");}catch(Exception ex){setStatus("Gagal menyimpan key: "+ex.getMessage());}}).setNegativeButton("Hapus",(d,w)->{try{keyStore.clear();}catch(Exception ignored){}setStatus("Gemini API key dihapus.");}).setNeutralButton("Batal",null).show();}

    private void ensureRecognizer(){if(recognizer!=null)return;try{if(SpeechRecognizer.isRecognitionAvailable(this))recognizer=SpeechRecognizer.createSpeechRecognizer(this);}catch(Throwable t){recognizer=null;}}
    private void toggleVoice(){if(voiceMode){voiceMode=false;recognitionBusy=false;pendingListen=false;recognitionRetries=0;if(recognizer!=null)recognizer.cancel();if(tts!=null)tts.stop();mic.setText("MIC");setStatus("Mode suara dihentikan.");refreshState();return;}if(Build.VERSION.SDK_INT>=23&&ContextCompat.checkSelfPermission(this,Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.RECORD_AUDIO},REQ_MIC);return;}voiceMode=true;recognitionRetries=0;mic.setText("STOP MIC");refreshState();setStatus("🎙 Siap. Bicaralah setelah muncul 'Mendengarkan…'");listen();}
    private void listen(){if(!voiceMode||recognitionBusy||speaking)return;if(Build.VERSION.SDK_INT>=23&&ContextCompat.checkSelfPermission(this,Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.RECORD_AUDIO},REQ_MIC);return;}ensureRecognizer();if(recognizer==null){setStatus("⚠ Mesin pengenal suara tidak tersedia. Pastikan Google Speech Services aktif.");voiceMode=false;mic.setText("MIC");refreshState();return;}try{recognitionBusy=true;Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"id-ID");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_PREFERENCE,"id-ID");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,false);i.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,5);i.putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS,2500);i.putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_POSSIBLY_COMPLETE_SILENCE_LENGTH_MILLIS,1800);i.putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_MINIMUM_LENGTH_MILLIS,800);recognizer.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle p){setStatus("🎙 Mendengarkan… silakan bicara sekarang");}public void onBeginningOfSpeech(){recognitionRetries=0;setStatus("🎙 Saya mendengar suara Anda…");}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){setStatus("🧠 Memahami ucapan…");}public void onError(int e){recognitionBusy=false;String msg=errorText(e);if(!voiceMode)return;if(e==SpeechRecognizer.ERROR_NO_MATCH||e==SpeechRecognizer.ERROR_SPEECH_TIMEOUT){if(recognitionRetries<3){recognitionRetries++;setStatus(msg+" Mencoba lagi ("+recognitionRetries+"/3)…");postListen(900);return;}setStatus(msg+" Silakan bicara lebih jelas dan dekat ke mikrofon.");recognitionRetries=0;postListen(1200);return;}if(e==SpeechRecognizer.ERROR_RECOGNIZER_BUSY){postListen(1200);return;}setStatus(msg+" Coba lagi.");postListen(1500);}public void onResults(Bundle r){recognitionBusy=false;recognitionRetries=0;ArrayList<String> a=r.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(a==null||a.isEmpty()||a.get(0)==null||a.get(0).trim().isEmpty()){setStatus("⚠ Ucapan kosong. Silakan bicara lagi.");postListen(800);return;}String heard=a.get(0).trim();command.setText(heard);setStatus("🗣 Anda: "+heard+"\n🧠 LUNA sedang memproses…");runCommand(heard);}public void onPartialResults(Bundle p){}public void onEvent(int t,Bundle p){}});recognizer.startListening(i);}catch(Throwable t){recognitionBusy=false;setStatus("⚠ Gagal memulai mikrofon: "+t.getMessage());postListen(1500);}}
    private String errorText(int e){switch(e){case SpeechRecognizer.ERROR_AUDIO:return "⚠ Mikrofon tidak dapat digunakan.";case SpeechRecognizer.ERROR_CLIENT:return "⚠ Pengenal suara berhenti.";case SpeechRecognizer.ERROR_INSUFFICIENT_PERMISSIONS:return "⚠ Izin mikrofon belum diberikan.";case SpeechRecognizer.ERROR_NETWORK:return "⚠ Koneksi layanan suara bermasalah.";case SpeechRecognizer.ERROR_NETWORK_TIMEOUT:return "⚠ Waktu layanan suara habis.";case SpeechRecognizer.ERROR_NO_MATCH:return "⚠ Ucapan belum dikenali.";case SpeechRecognizer.ERROR_RECOGNIZER_BUSY:return "⚠ Pengenal suara sedang sibuk.";case SpeechRecognizer.ERROR_SERVER:return "⚠ Server pengenal suara bermasalah.";case SpeechRecognizer.ERROR_SPEECH_TIMEOUT:return "⚠ Tidak terdengar ucapan.";default:return "⚠ Pengenal suara mengalami error ("+e+").";}}
    private void postListen(long ms){new Handler(Looper.getMainLooper()).postDelayed(()->listen(),ms);}

    private void runCommand(String raw){String c=raw==null?"":raw.trim();if(c.isEmpty()){setStatus("Ketik atau ucapkan pertanyaan/perintah.");return;}if(running){setStatus("LUNA masih memproses. Tekan STOP jika ingin membatalkan.");return;}running=true;pendingListen=voiceMode;setStatus("🧠 LUNA sedang memahami…");worker.execute(()->{try{LunaAccessibilityService svc=LunaAccessibilityService.get();LunaAgent agent=new LunaAgent(this,svc,keyStore,new LunaAgent.Callback(){public void status(String s){runOnUiThread(()->setStatus(s));}public void speak(String s){runOnUiThread(()->speakLuna(s));}public boolean confirm(JSONObject p){final boolean[] ok={false};CountDownLatch h=new CountDownLatch(1);runOnUiThread(()->{new AlertDialog.Builder(MainActivity.this).setTitle("Konfirmasi LUNA").setMessage("LUNA akan melakukan tindakan yang memerlukan persetujuan. Lanjutkan?").setNegativeButton("Batal",(d,w)->{ok[0]=false;h.countDown();}).setPositiveButton("Lanjutkan",(d,w)->{ok[0]=true;h.countDown();}).setOnCancelListener(d->{ok[0]=false;h.countDown();}).show();});try{h.await();}catch(InterruptedException e){Thread.currentThread().interrupt();}return ok[0];}public void finished(){runOnUiThread(()->{running=false;if(voiceMode&&!speaking&&pendingListen){pendingListen=false;postListen(900);}else refreshState();});}});agent.run(c);}catch(Exception e){runOnUiThread(()->{running=false;setStatus("⚠ LUNA: "+(e.getMessage()==null?e.toString():e.getMessage()));});}});}
    private void speakLuna(String s){if(s==null||s.trim().isEmpty())return;setStatus("🗣 LUNA: "+s);if(!ttsReady||tts==null){setStatus("⚠ Jawaban LUNA siap, tetapi Text-to-Speech belum siap: "+s);return;}pendingListen=voiceMode;int r=tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"LUNA_RESPONSE");if(r!=TextToSpeech.SUCCESS){speaking=false;setStatus("⚠ Gagal mengucapkan jawaban. Jawaban LUNA: "+s);if(voiceMode)postListen(1000);}}
    private void stopAll(){voiceMode=false;running=false;pendingListen=false;recognitionBusy=false;recognitionRetries=0;if(recognizer!=null)recognizer.cancel();if(tts!=null)tts.stop();LunaAccessibilityService svc=LunaAccessibilityService.get();if(svc!=null)svc.stopNow();mic.setText("MIC");setStatus("■ STOP — semua proses LUNA dihentikan.");refreshState();}
    private void setStatus(String s){if(status!=null)status.setText(s);}
    @Override protected void onResume(){super.onResume();refreshState();}
    @Override public void onRequestPermissionsResult(int requestCode,String[] permissions,int[] grants){super.onRequestPermissionsResult(requestCode,permissions,grants);if(requestCode==REQ_MIC){if(grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED){voiceMode=true;mic.setText("STOP MIC");refreshState();setStatus("✓ Izin mikrofon aktif. 🎙 Silakan bicara.");postListen(500);}else{voiceMode=false;setStatus("⚠ Izin mikrofon ditolak. Aktifkan izin Mikrofon untuk LUNA.");}}}
    @Override protected void onDestroy(){voiceMode=false;if(recognizer!=null)recognizer.destroy();if(tts!=null)tts.shutdown();worker.shutdownNow();super.onDestroy();}
}
